#!/system/bin/sh
#
# Copyright (C) 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Kernel script by TamCore
#

# Sweep2Wake
# possible values:
# 0 = off
# 1 = on
# 2 = on without button backlights
SWEEP2WAKE=1

# Badass
# possible values
# 1 = performance
# 2 = balanced
# 3 = battery saving
BADASS=2

# USB fast charge
# 0 - disabled (default)
# 1 - substitute AC to USB charging always
# 2 - substitute AC to USB charging only if no USB peripheral is detected
FASTCHG=0

# Wifi Screen-Off Power Management
PM_FAST=1

# FSync Control
FSYNC=1

### DO NOT CHANGE ANYTHING BELLOW THIS LINE! ###
L="log -p i -t $0"

$L "setting sweep2wake to ${SWEEP2WAKE}"
echo ${SWEEP2WAKE} > /sys/android_touch/sweep2wake

$L "setting fast charge to ${FASTCHG}"
echo ${FASTCHG} > /sys/kernel/fast_charge/force_fast_charge

$L "setting PM_FAST to ${PM_FAST}"
echo ${PM_FAST} > /sys/module/bcmdhd/parameters/wifi_pm

$L "setting fsync controll to ${FSYNC}"
echo ${FSYNC} > /sys/class/misc/fsynccontrol/fsync_enabled

CUR_GOV="`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`"
echo badass > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
case ${BADASS} in
	1)
		$L "badass: setting performance oriented configuration"
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1512000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 120 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 8 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 4 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 150 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 50 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 300 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
		echo 450 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
	;;
	2)
		$L "badass: setting balanced configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 130 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 100 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 14 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 6 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 260 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 180 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 700 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
		echo 500 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
	;;
	3)
		$L "badass: setting battery saving configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 140 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 110 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 20 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
		echo 300 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_threshold;
		echo 250 > /sys/devices/system/cpu/cpufreq/badass/gpu_semi_busy_clr_threshold;
		echo 750 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_threshold;
		echo 600 > /sys/devices/system/cpu/cpufreq/badass/gpu_busy_clr_threshold;
	;;
esac
echo ${CUR_GOV} > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
